import type { Metadata } from 'next'
import './globals.css'
import { Header } from '@/components/Header'
import { poppins } from './fonts'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${poppins.className} `}>
				<Header />
				{children}
			</body>
		</html>
	)
}
